config_version: '1.1'

# 玩家传送界面的配置
playertp:
  line: 6     # 菜单有多少行, 1-6
  title: ':offset_-8::hhplayertp_menu:'
  items:                  # fun: cmd, next_page, prev_page, player
    'return':
      display: '返回'
      slot: [7,8]
      material: 'KELP'
      custom_model_data: 10000007
      fun: 'cmd'
      cmd: 'trmenu open 主菜单'
    'next_page':
      slot: [52]
      material: 'ARROW'
      custom_model_data: 10008
      fun: 'next_page'
    'prev_page':
      slot: [46]
      material: 'ARROW'
      custom_model_data: 10008
      fun: 'prev_page'
    'player':
      slot: [9-44]
      fun: 'player'
      left: 'tpa %player_name%'                     # %player_name% 表示目标玩家的名字
      right: 'tpahere %player_name%'                # %player_name% 表示目标玩家的名字
  chat_box_text:      # 玩家聊天框内容, 指的是: 点击之后发送到目标玩家的消息(支持papi变量, 变量所有者为   发出请求的玩家)
    - ''
    - '&6  玩家[&4%player_name%&6]向你发送传送请求'     # %player_name% 发出请求的玩家的名字
    - ''
    - '  [accept]        [deny]'                    # [accept]是同意传送按钮 [deny]是拒绝传送按钮, 不要随便乱改, 你可以修改到其他行, 但是不能改为其他值
    - ':hhplayertptip:'
  # 下面的就不支持papi变量了
  accept:
    show_text: '&2[同意]'                 # 显示文本
    hover_show_text: '&2点击同意传送'       # 悬停显示文本
    cmd: 'tpaccept'                     # 点击执行的指令
  deny:
    show_text: '&4[拒绝]'                 # 显示文本
    hover_show_text: '&4点击拒绝传送'       # 悬停显示文本
    cmd: 'tpdeny'                       # 点击执行的指令

